// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

#ifndef DIAGNOSTIC_CODES_GEN_HPP
#define DIAGNOSTIC_CODES_GEN_HPP

namespace Alpha
{
enum class DiagnosticCodes
{
	ASSIGNMENT_LHS_NOT_LVALUE,
	ASSIGNMENT_OF_FUNC,
	ASSIGNMENT_OF_LIBFUNC,
};
} // namespace Alpha
#endif // DIAGNOSTIC_CODES_GEN_HPP
