// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

#ifndef DIAGNOSTIC_CODES_GEN_HPP
#define DIAGNOSTIC_CODES_GEN_HPP

#include <diagnostics/diagnostic_engine.hpp>
#include <string>
#include <core/basics.hpp>
#include <core/source_location.hpp>

namespace Alpha
{
class DiagnosticReporter : private Immobile
{
public:
	explicit DiagnosticReporter(DiagnosticEngine *const de)
		: diagnostic_engine_(de) {}

	void report_assignment_lhs_not_lvalue(const std::string &lhs_type, SourceLocation lhs_loc);
	void report_assignment_of_func(const std::string &func_name, SourceLocation assign_loc, SourceLocation func_def_loc);
	void report_assignment_of_libfunc(const std::string &func_name, SourceLocation assign_loc);

private:
	DiagnosticEngine *const diagnostic_engine_;
};
} // namespace Alpha

#endif // DIAGNOSTIC_CODES_GEN_HPP
