// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS
// FILE IN ORDER TO MAKE IT MORE READABLE.

#include <diagnostics/diagnostic_reporter.gen.hpp

#include <list>
#include <string>
#include <core/source_location.hpp>

namespace Alpha
{
void DiagnosticReporter::report_assignment_lhs_not_lvalue(const std::string &lhs_type, const SourceLocation lhs_loc)
{
	const std::string primary = FMT::format("Lvalue required as left operand of assignment. Left operand's expression type is `{0}`", lhs_type);
	diagnostic_engine_->report(Issue::Type::ERROR, primary, lhs_loc);
}

void DiagnosticReporter::report_assignment_of_func(const std::string &func_name, const SourceLocation assign_loc, const SourceLocation func_def_loc)
{
	const std::string primary = FMT::format("Assignment of function `{0}`", func_name);
	const std::string note0 = FMT::format("Function `{0}` defined here", func_name);
	diagnostic_engine_->report(Issue::Type::ERROR, primary, assign_loc, std::list{Note{note0, func_def_loc}});
}

void DiagnosticReporter::report_assignment_of_libfunc(const std::string &func_name, const SourceLocation assign_loc)
{
	const std::string primary = FMT::format("Assignment of library function `{0}`", func_name);
	diagnostic_engine_->report(Issue::Type::ERROR, primary, assign_loc);
}

} // namespace Alpha
