import os
import utils
from models import Diagnostic

_generated_file_header_warning = (
    "// This file was generated by `diagnostic_generator`.\n"
    "// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN."
)

_format_recommendation = (
    "// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS\n"
    "// FILE IN ORDER TO MAKE IT MORE READABLE."
)

_source_location_header_path = r"core/source_location.hpp"

_namespace = "Alpha"

_diagnostic_reporter_class_name = 'DiagnosticReporter'


class CppGenerator:

    def __init__(self, cli_args, diagnostics: list[Diagnostic]):
        self.diagnostics = diagnostics
        self.cli_args = cli_args
        self.codes_header_filename = f"{cli_args.outfile_prefix}_codes.gen.hpp"
        self.reporter_header_filename = f"{cli_args.outfile_prefix}_reporter.gen.hpp"
        self.reporter_source_filename = f"{cli_args.outfile_prefix}_reporter.gen.cpp"
        self.source_location_header_path = r"core/source_location.hpp"

    @staticmethod
    def _extract_unique_args(arg_list: list[str]) -> list[str]:
        result = []
        for arg in arg_list:
            if arg not in result:
                result.append(arg)
        return result

    @staticmethod
    def _merge_message_args(diagnostic: Diagnostic) -> list[str]:
        all_args = diagnostic.primary.args + [arg for note in diagnostic.notes for arg in note.args]
        return CppGenerator._extract_unique_args(all_args)

    @staticmethod
    def _merge_locations(diagnostic: Diagnostic) -> list[str]:
        return [diagnostic.primary.location] + [note.location for note in diagnostic.notes]

    @staticmethod
    def _generate_arg_list(diagnostic: Diagnostic, for_impl: bool) -> str:
        string_arg_list = CppGenerator._merge_message_args(diagnostic)
        string_args = ','.join(f"const std::string &{arg}" for arg in string_arg_list)
        location_arg_list = CppGenerator._merge_locations(diagnostic)
        return (
            ', '.join(f"const std::string &{arg}" for arg in string_arg_list) +
            (', ' if string_args else '') +  # We put , after string are (if there are any)
            ', '.join(f"{'const ' if for_impl else ''}SourceLocation {loc}" for loc in location_arg_list)
        )

    @staticmethod
    def _generate_declarations(diagnostics: list[Diagnostic]):
        declarations = []
        for d in diagnostics:
            ret_type = "void"
            func_name = "report_" + d.name.lower()
            arg_list = CppGenerator._generate_arg_list(d, False)
            declaration = f"{ret_type} {func_name}({arg_list});"
            declarations.append(declaration)
        return declarations

    @staticmethod
    def _generate_definitions(diagnostics: list[Diagnostic]):
        definitions = []
        for d in diagnostics:
            ret_type = "void"
            func_name = "report_" + d.name.lower()
            arg_list = CppGenerator._generate_arg_list(d, True)
            definition = f"{ret_type} {_diagnostic_reporter_class_name}::{func_name}({arg_list})\n"
            definition += f"{{\n"
            definition += f'\tconst std::string primary = FMT::format("{d.primary.message}"{", " if d.primary.args else ''}{", ".join(d.primary.args)});\n'
            for i, note in enumerate(d.notes):
                definition += f'\tconst std::string note{i} = FMT::format("{note.message}"{", " if note.args else ''}{", ".join(note.args)});\n'
            definition += f"\tdiagnostic_engine_->report(Issue::Type::{d.type}, primary, {d.primary.location}"
            for i, note in enumerate(d.notes):
                definition += f", std::list{{Note{{note{i}, {note.location}}}}}"
            definition += f");\n"
            definition += f"}}\n"
            definitions.append(definition)

        return definitions

    def generate_codes_header_file(self) -> None:
        temp_filename = utils.temp_version(self.codes_header_filename)
        guard_name = self.codes_header_filename.upper().replace('.', '_')
        enum_entries = "".join(f"\t{d.name},\n" for d in self.diagnostics)

        fout = open(temp_filename, 'w')
        fout.write(
            f"{_generated_file_header_warning}\n"
            f"\n"
            f"#ifndef {guard_name}\n"
            f"#define {guard_name}\n"
            f"\n"
            f"namespace {_namespace}\n"
            f"{{\n"
            f"enum class DiagnosticCodes\n"
            f"{{\n"
            f"{enum_entries}"
            f"}};\n"
            f"}} // namespace {_namespace}\n"
            f"#endif // {guard_name}\n"
        )
        os.rename(temp_filename, self.codes_header_filename)

    def generate_reporter_header_file(self) -> None:
        temp_filename = utils.temp_version(self.reporter_header_filename)
        guard_name = self.codes_header_filename.upper().replace('.', '_')
        method_declarations = f"{'\n'.join(f"\t{line}" for line in CppGenerator._generate_declarations(self.diagnostics))}\n"

        fout = open(temp_filename, 'w')
        fout.write(
            f"{_generated_file_header_warning}\n"
            f"\n"
            f"#ifndef {guard_name}\n"
            f"#define {guard_name}\n"
            f"\n"
            f"#include <diagnostics/diagnostic_engine.hpp>\n"
            f"#include <string>\n"
            f"#include <core/basics.hpp>\n"
            f"#include <{_source_location_header_path}>\n"
            f"\n"
            f"namespace {_namespace}\n"
            f"{{\n"
            f"class {_diagnostic_reporter_class_name} : private Immobile\n"
            f"{{\n"
            f"public:\n"
            f"\texplicit {_diagnostic_reporter_class_name}(DiagnosticEngine *const de)\n"
            f"\t\t: diagnostic_engine_(de) {{}}\n"
            f"\n"
            f"{method_declarations}"
            f"\n"
            f"private:\n"
            f"\tDiagnosticEngine *const diagnostic_engine_;\n"
            f"}};\n"
            f"}} // namespace {_namespace}\n"
            f"\n"
            f"#endif // {guard_name}\n"
        )
        os.rename(temp_filename, self.reporter_header_filename)

    def generate_reporter_source_file(self):
        temp_filename = utils.temp_version(self.reporter_source_filename)
        method_definitions = f"{'\n'.join(f"{line}" for line in CppGenerator._generate_definitions(self.diagnostics))}\n"
        with open(temp_filename, 'w') as fout:
            fout.write(
                f"{_generated_file_header_warning}\n"
                f"\n"
                f"{_format_recommendation}\n"
                f"\n"
                f"#include <diagnostics/{self.reporter_header_filename}\n"
                f"\n"
                f"#include <list>\n"
                f"#include <string>\n"
                f"#include <{_source_location_header_path}>\n"
                f"\n"
                f"namespace {_namespace}\n"
                f"{{\n"
                f"{method_definitions}"
                f"}} // namespace {_namespace}\n"
            )
        os.rename(temp_filename, self.reporter_source_filename)

    def generate_all_files(self):
        original_path = os.getcwd()

        os.chdir(self.cli_args.out_include)
        self.generate_codes_header_file()
        self.generate_reporter_header_file()

        os.chdir(self.cli_args.out_src)
        self.generate_reporter_source_file()

        os.chdir(original_path)
