IROPCODE_INFO:
  operands: int    # Implicit default is 0 (if not specified).
  uses_label: bool # Implicit default is false (if not specified).

IROPCODE_OPTIMIZATION_FLAGS: [ foldable, trimmable ]

IROPCODE_LIST:
  ASSIGN:
    operands: 2
    optimizations: [ trimmable ]

  UMINUS:
    operands: 1
    optimizations: [ foldable ]

  ADD:
    operands: 2
    optimizations: [ foldable, trimmable ]

  SUB:
    operands: 2
    optimizations: [ foldable, trimmable ]

  MUL:
    operands: 2
    optimizations: [ foldable, trimmable ]

  DIV:
    operands: 2
    optimizations: [ foldable, trimmable ]

  MOD:
    operands: 2
    optimizations: [ foldable, trimmable ]

  NOT:
    operands: 1
    optimizations: [ foldable ]

  AND:
    operands: 2
    optimizations: [ foldable ]

  OR:
    operands: 2
    optimizations: [ foldable ]

  IF_EQ:
    operands: 2
    uses_label: true
    optimizations: [ foldable, trimmable ]

  IF_NEQ:
    operands: 2
    uses_label: true
    optimizations: [ foldable, trimmable ]

  IF_LT:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  IF_LTE:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  IF_GT:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  IF_GTE:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  JUMP:
    uses_label: true
      
  TABLECREATE:

  TABLESETELEM:
    operands: 2

  TABLEGETELEM:
    operands: 2

  FUNCSTART:

  FUNCEND:

#      define IOPCODES_WITHOUT_LABEL \
#      X(CALL)                    \
#      X(PARAM)                   \
#      X(RETURN)                  \
#      X(GETRETVAL)               \

