IROPCODE_INFO_ENUMS:
  Need: [ NONE, OPTIONAL, REQUIRED ]
  TEST: [ t1, T4, test2 ]

IROPCODE_INFO:
  requires_result: bool # Must provide a non-null `result` operand when emitting this opcode (false if omitted)
  requires_arg1: Need # Must provide a non-null `arg1`   operand when emitting this opcode (false if omitted)
  requires_arg2: Need # Must provide a non-null `arg2`   operand when emitting this opcode (false if omitted)
  operands: int  # Number of explicit source operands, not counting `result` (0 if omitted)
  uses_label: bool # Instruction expects a valid jump/branch label (false if omitted)

IROPCODE_OPTIMIZATION_FLAGS: [ foldable, trimmable ]

IROPCODE_LIST:
  ASSIGN:
    requires_arg1: OPTIONAL
    operands: 2
    optimizations: [ trimmable ]

  UMINUS:
    operands: 1
    optimizations: [ foldable ]

  ADD:
    operands: 2
    optimizations: [ foldable, trimmable ]

  SUB:
    operands: 2
    optimizations: [ foldable, trimmable ]

  MUL:
    operands: 2
    optimizations: [ foldable, trimmable ]

  DIV:
    operands: 2
    optimizations: [ foldable, trimmable ]

  MOD:
    operands: 2
    optimizations: [ foldable, trimmable ]

  NOT:
    operands: 1
    optimizations: [ foldable ]

  AND:
    operands: 2
    optimizations: [ foldable ]

  OR:
    operands: 2
    optimizations: [ foldable ]

  IF_EQ:
    operands: 2
    uses_label: true
    optimizations: [ foldable, trimmable ]

  IF_NEQ:
    operands: 2
    uses_label: true
    optimizations: [ foldable, trimmable ]

  IF_LT:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  IF_LTE:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  IF_GT:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  IF_GTE:
    operands: 2
    uses_label: true
    optimizations: [ foldable ]

  JUMP:
    uses_label: true

  TABLECREATE:

  TABLESETELEM:
    operands: 2

  TABLEGETELEM:
    operands: 2

  PARAM:
    operands: 1

  CALL:

  GETRETVAL:

  RETURN:

  FUNCSTART:

  FUNCEND:

