// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS
// FILE IN ORDER TO MAKE IT MORE READABLE.

#ifndef __IR_OPCODE_INFO_TRAITS_HPP
#define __IR_OPCODE_INFO_TRAITS_HPP

#include "ir_opcode.hpp"

enum class Need
{
	REQUIRED,
	OPTIONAL,
	NONE,
}
enum class TEST
{
	test2,
	T4,
	t1,
}

// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr int operands(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case ASSIGN: return 2;
	case UMINUS: return 1;
	case ADD: return 2;
	case SUB: return 2;
	case MUL: return 2;
	case DIV: return 2;
	case MOD: return 2;
	case NOT: return 1;
	case AND: return 2;
	case OR: return 2;
	case IF_EQ: return 2;
	case IF_NEQ: return 2;
	case IF_LT: return 2;
	case IF_LTE: return 2;
	case IF_GT: return 2;
	case IF_GTE: return 2;
	case TABLESETELEM: return 2;
	case TABLEGETELEM: return 2;
	case PARAM: return 1;
	default: return 0;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr Need requires_arg1(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
case ASSIGN: return OPTIONAL;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr Need requires_arg2(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
case ASSIGN: return OPTIONAL;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr bool requires_result(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	default: return false;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr bool uses_label(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case IF_EQ: return true;
	case IF_NEQ: return true;
	case IF_LT: return true;
	case IF_LTE: return true;
	case IF_GT: return true;
	case IF_GTE: return true;
	case JUMP: return true;
	default: return false;
	}
}

} // namespace alpha::ir::info_traits

#endif // __IR_OPCODE_INFO_TRAITS_HPP

