import os
from functools import partial
from typing import TextIO
from shared_config import ConfigArguments
from yaml_parser import IROpcodeInfo, YamlParserProducts, InfoFieldTypes, attach_context
from pathlib import Path


class CPPGenerator:
    ALPHA_IR_OPCODES_MACRO: str = "ALPHA_IROPCODES"
    PROJECT_NAMESPACE: str = "alpha"
    IR_NAMESPACE: str = f"{PROJECT_NAMESPACE}::ir"
    INFO_TRAITS_NAMESPACE: str = f"{IR_NAMESPACE}::info_traits"
    OPT_TRAITS_NAMESPACE: str = f"{IR_NAMESPACE}::opt_traits"

    def __init__(
            self,
            config_args: ConfigArguments,
            yaml_parser_products: YamlParserProducts,
            opcode_enum_name: str
    ):
        self._config_args = config_args
        self._opcode_enum_name = opcode_enum_name
        self._iropcode_dict = yaml_parser_products.opcode_dict
        self._available_optimization_set = yaml_parser_products.available_opts
        self._available_info_set = yaml_parser_products.available_info_set
        self._available_info_enums = yaml_parser_products.available_info_enums

    @property
    def out_header_filename(self):
        return os.path.basename(self._out_header_filepath)

    @staticmethod
    def write_autogen_warning(fout: TextIO):
        fout.write(
            f"// This file was generated by `diagnostic_generator`.\n"
            f"// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.\n"
            f"\n"
            f"// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS\n"
            f"// FILE IN ORDER TO MAKE IT MORE READABLE.\n"
        )

    @staticmethod
    def include_guard(filepath: Path) -> str:
        return os.path.basename(filepath).replace(".", "_").upper()

    @staticmethod
    def write_header_opening(fout: TextIO, include_guard: str):
        fout.write(
            f"#ifndef {include_guard}\n"
            f"#define {include_guard}\n"
        )

    @staticmethod
    def write_header_closing(fout: TextIO, include_guard: str):
        fout.write(
            f"#endif // {include_guard}\n"
        )

    def write_opcode_def_inclusion(self, fout: TextIO):
        fout.write(
            f'#include "{os.path.basename(self._config_args.out_opcode_header_filepath)}"'
            f"\n"
        )

    def write_ir_opcode_x_macro(self, fout: TextIO):
        iropcode_name_list = list(self._iropcode_dict.keys())
        fout.write(f"#define {CPPGenerator.ALPHA_IR_OPCODES_MACRO} \\\n")
        for i in range(len(iropcode_name_list)):
            iropcode_name = iropcode_name_list[i]
            is_last_enum = i + 1 == len(iropcode_name_list)
            suffix = "\\" if not is_last_enum else ""
            fout.write(f'\tX({iropcode_name}) {suffix}\n')

    def write_ir_opcodes(self, fout: TextIO):
        fout.write(
            f"namespace {CPPGenerator.IR_NAMESPACE}\n"
            f"{{\n"
            f"enum class {self._opcode_enum_name}\n"
            f"{{\n"
            f"\t#define X(iropcode) iropcode,\n"
            f"\t{CPPGenerator.ALPHA_IR_OPCODES_MACRO}\n"
            f"\t#undef  X\n"
            f"}};\n"
            f"}} // namespace {CPPGenerator.IR_NAMESPACE}\n"
        )

    def write_ir_opcode_to_string_decl(self, fout: TextIO):
        fout.write(
            f"#include <string>\n"
            f"namespace {CPPGenerator.IR_NAMESPACE}\n"
            f"{{\n"
            f"[[nodiscard]] std::string to_string({self._opcode_enum_name} opc) noexcept;\n"
            f"}} // namespace {CPPGenerator.IR_NAMESPACE}\n"
        )
    def write_ir_opcode_to_string_impl(self, fout: TextIO):
        fout.write(
            f'#include <parser/{os.path.basename(self._config_args.out_opcode_header_filepath)}>\n'
            f'#include <utils/misc.hpp>\n'
            f"namespace {CPPGenerator.IR_NAMESPACE}\n"
            f"{{\n"
            f"std::string to_string(const {self._opcode_enum_name} opc) noexcept\n"
            f"{{\n"
            f"\tswitch (opc)\n"
            f"\t{{\n"
            f"\t\t#define X(opc) case {self._opcode_enum_name}::opc: return Utils::str_to_lower(#opc);\n"
            f"\t\t{CPPGenerator.ALPHA_IR_OPCODES_MACRO}\n"
            f"\t\t#undef  X\n"
            f"\t\tdefault:\n"
            f"\t\t\tUNREACHABLE(FMT::format(\n"
            f'\t\t\t\t"BUG: Unknown Opcode. Opcode\'s int value = `{{}}`", static_cast<int>(opc)));\n'
            f"\t}}\n"
            f"}}\n"
            f"}} // namespace {CPPGenerator.IR_NAMESPACE}\n"
        )

    def write_primitive_constexpr_info_check_function(self, fout:TextIO, info_trait: InfoFieldTypes):
        if info_trait.type == "bool":
            default_ret_type = "false"
        elif info_trait.type == "int":
            default_ret_type = "0"
        elif info_trait.type == "str":
            default_ret_type = '""'
        else:
            raise RuntimeError(attach_context(f"unknown info_tait.type: `{info_trait.type}`"))

        return_type = 'const char *' if info_trait.type == "str" else info_trait.type

        fout.write(
            f"// Follows definitions of all info Traits-Functions of {self._opcode_enum_name}\n"
            f"namespace {CPPGenerator.INFO_TRAITS_NAMESPACE}\n"
            f"{{\n"
        )
        fout.write(
            f"[[nodiscard]] constexpr {return_type} {info_trait.name}(const {self._opcode_enum_name} opc)\n"
            f"{{\n"
            f"\tusing enum {CPPGenerator.IR_NAMESPACE}::{self._opcode_enum_name};\n"
            f"\tswitch(opc)\n"
            f"\t{{\n"
        )

        for opc_name, opc_info in self._iropcode_dict.items():
            for info_field in opc_info.info_field_set:
                if info_field.name == info_trait.name:
                    fout.write(f"\tcase {opc_name}: return {info_field.value};\n")

        fout.write(
            f"\tdefault: return {default_ret_type};\n"
            f"\t}}\n"
            f"}}\n"
            f"\n"
        )
        fout.write(
            f"}} // namespace {CPPGenerator.INFO_TRAITS_NAMESPACE}\n"
        )

    def write_enum_constexpr_info_check_function(self, fout:TextIO, info_trait:InfoFieldTypes):
        fout.write(
            f"// Follows definitions of all info Traits-Functions of {self._opcode_enum_name}\n"
            f"namespace {CPPGenerator.INFO_TRAITS_NAMESPACE}\n"
            f"{{\n"
        )
        fout.write(
            f"[[nodiscard]] constexpr {info_trait.type} {info_trait.name}(const {self._opcode_enum_name} opc)\n"
            f"{{\n"
            f"\tusing enum {CPPGenerator.IR_NAMESPACE}::{self._opcode_enum_name};\n"
            f"\tswitch(opc)\n"
            f"\t{{\n"
        )
        for opc_name, opc_info in self._iropcode_dict.items():
            for info_field in opc_info.info_field_set:
                if info_field.type == info_trait.type:
                    fout.write(f"case {opc_name}: return {info_field.value};\n")

        fout.write(
            f"\t}}\n"
            f"}}\n"
            f"\n"
        )
        fout.write(
            f"}} // namespace {CPPGenerator.INFO_TRAITS_NAMESPACE}\n"
        )

    def write_constexpr_info_check_function(self, fout: TextIO, info_trait: InfoFieldTypes):
        if info_trait.type in self._available_info_enums:
            self.write_enum_constexpr_info_check_function(fout, info_trait)
        else:
            self.write_primitive_constexpr_info_check_function(fout, info_trait)


    def write_constexpr_optim_flag_function(self, fout: TextIO, opt_name):
        fout.write(
            f"[[nodiscard]] constexpr bool is_{opt_name}(const {self._opcode_enum_name} opc)\n"
            f"{{\n"
            f"\tusing enum {CPPGenerator.IR_NAMESPACE}::{self._opcode_enum_name};\n"
            f"\tswitch(opc)\n"
            f"\t{{\n"
        )
        for opc_name, opc_info in self._iropcode_dict.items():
            if opc_info.optimizations is None:
                continue
            if opt_name in opc_info.optimizations:
                    fout.write(f"\tcase {opc_name}: return true;\n")

        fout.write(
            f"\tdefault: return false;\n"
            f"\t}}\n"
            f"}}\n"
            f"\n"
        )

    @staticmethod
    def write_info_trait_enum(fout:TextIO, enum_name:str, enum_values:set[str]):
        fout.write(
            f"enum class {enum_name}\n"
            f"{{\n"
        )
        for value in enum_values:
            fout.write(
                f"\t{value},\n"
            )

        fout.write(
            f"}}\n"
        )

    def write_ir_info_traits_definitions(self, fout: TextIO):
        sorted_available_info_set = sorted(
            self._available_info_set,
            key=lambda info: info.name
        )
        for info_trait in sorted_available_info_set:
            self.write_constexpr_info_check_function(fout, info_trait)

    def write_ir_optim_trait_definitions(self, fout: TextIO):
        fout.write(
            f"// Follows definitions of all Optimization Traits-Functions of {self._opcode_enum_name}\n"
            f"namespace {CPPGenerator.OPT_TRAITS_NAMESPACE}\n"
            f"{{\n"
        )
        sorted_available_optimization_set = sorted(self._available_optimization_set)
        for opt_name in sorted_available_optimization_set:
            self.write_constexpr_optim_flag_function(fout, opt_name)

        fout.write(
            f"}} // namespace {CPPGenerator.OPT_TRAITS_NAMESPACE}\n"
        )

    def write_ir_info_trait_enum_definitions(self, fout:TextIO):
        for enum_name, enum_values in self._available_info_enums.items():
            CPPGenerator.write_info_trait_enum(fout, enum_name, enum_values)


    def run(self):
        def run_generation_calls(fout: TextIO, calls):
            for call in calls:
                call()
                fout.write("\n")

        with open(self._config_args.out_opcode_header_filepath, "w") as fout:
            opcode_def_calls = [
                partial(CPPGenerator.write_autogen_warning, fout),
                partial(CPPGenerator.write_header_opening, fout,
                        CPPGenerator.include_guard(self._config_args.out_opcode_header_filepath)),
                partial(self.write_ir_opcode_x_macro, fout),
                partial(self.write_ir_opcodes, fout),
                partial(self.write_ir_opcode_to_string_decl, fout),
                partial(CPPGenerator.write_header_closing, fout,
                        CPPGenerator.include_guard(self._config_args.out_opcode_header_filepath)),
            ]
            run_generation_calls(fout, opcode_def_calls)

        with open(self._config_args.out_opcode_source_filepath, "w") as fout:
            opcode_def_calls = [
                partial(CPPGenerator.write_autogen_warning, fout),
                partial(self.write_ir_opcode_to_string_impl, fout),
            ]
            run_generation_calls(fout, opcode_def_calls)

        with open(self._config_args.out_opcode_info_traits_header_filepath, "w") as fout:
            opcode_info_traits_def_calls = [
                partial(CPPGenerator.write_autogen_warning, fout),
                partial(CPPGenerator.write_header_opening, fout, CPPGenerator.include_guard(
                    self._config_args.out_opcode_info_traits_header_filepath)),
                partial(self.write_opcode_def_inclusion, fout),
                partial(self.write_ir_info_trait_enum_definitions, fout),
                partial(self.write_ir_info_traits_definitions, fout),
                partial(CPPGenerator.write_header_closing, fout, CPPGenerator.include_guard(
                    self._config_args.out_opcode_info_traits_header_filepath)),
            ]
            run_generation_calls(fout, opcode_info_traits_def_calls)

        with open(self._config_args.out_opcode_opt_traits_header_filepath, "w") as fout:
            opcode_opt_traits_def_calls = [
                partial(CPPGenerator.write_autogen_warning, fout),
                partial(CPPGenerator.write_header_opening, fout, CPPGenerator.include_guard(
                    self._config_args.out_opcode_opt_traits_header_filepath)),
                partial(self.write_opcode_def_inclusion, fout),
                partial(self.write_ir_optim_trait_definitions, fout),
                partial(CPPGenerator.write_header_closing, fout, CPPGenerator.include_guard(
                    self._config_args.out_opcode_opt_traits_header_filepath)),
            ]
            run_generation_calls(fout, opcode_opt_traits_def_calls)
