// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS
// FILE IN ORDER TO MAKE IT MORE READABLE.

#ifndef IR_OPCODES_OPTS_TRAITS_HPP
#define IR_OPCODES_OPTS_TRAITS_HPP

#include "ir_opcode.hpp"

// Follows definitions of all Optimization Traits-Functions of Opcode
namespace alpha::ir::opt_traits
{
[[nodiscard]] constexpr bool is_foldable(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case UMINUS: return true;
	case ADD: return true;
	case SUB: return true;
	case MUL: return true;
	case DIV: return true;
	case MOD: return true;
	case NOT: return true;
	case AND: return true;
	case OR: return true;
	case IF_EQ: return true;
	case IF_NEQ: return true;
	case IF_LT: return true;
	case IF_LTE: return true;
	case IF_GT: return true;
	case IF_GTE: return true;
	default: return false;
	}
}

[[nodiscard]] constexpr bool is_trimmable(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case ASSIGN: return true;
	case ADD: return true;
	case SUB: return true;
	case MUL: return true;
	case DIV: return true;
	case MOD: return true;
	case IF_EQ: return true;
	case IF_NEQ: return true;
	default: return false;
	}
}

} // namespace alpha::ir::opt_traits

#endif // IR_OPCODES_OPTS_TRAITS_HPP

