// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS
// FILE IN ORDER TO MAKE IT MORE READABLE.

#ifndef IR_OPCODE_INFO_TRAITS_HPP
#define IR_OPCODE_INFO_TRAITS_HPP

#include "ir_opcode.hpp"

enum class Need
{
	NONE,
	REQUIRED,
	OPTIONAL,
}

// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr Need arg1(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case ASSIGN: return REQUIRED;
	case UMINUS: return REQUIRED;
	case ADD: return REQUIRED;
	case SUB: return REQUIRED;
	case MUL: return REQUIRED;
	case DIV: return REQUIRED;
	case MOD: return REQUIRED;
	case NOT: return REQUIRED;
	case AND: return REQUIRED;
	case OR: return REQUIRED;
	case IF_EQ: return REQUIRED;
	case IF_NEQ: return REQUIRED;
	case IF_LT: return REQUIRED;
	case IF_LTE: return REQUIRED;
	case IF_GT: return REQUIRED;
	case IF_GTE: return REQUIRED;
	case JUMP: return REQUIRED;
	case TABLECREATE: return REQUIRED;
	case TABLESETELEM: return REQUIRED;
	case TABLEGETELEM: return REQUIRED;
	case PARAM: return REQUIRED;
	case CALL: return REQUIRED;
	case GETRETVAL: return REQUIRED;
	case RETURN: return REQUIRED;
	case FUNCSTART: return REQUIRED;
	case FUNCEND: return REQUIRED;
	default: return NONE;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr Need arg2(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case ASSIGN: return REQUIRED;
	case UMINUS: return REQUIRED;
	case ADD: return REQUIRED;
	case SUB: return REQUIRED;
	case MUL: return REQUIRED;
	case DIV: return REQUIRED;
	case MOD: return REQUIRED;
	case NOT: return REQUIRED;
	case AND: return REQUIRED;
	case OR: return REQUIRED;
	case IF_EQ: return REQUIRED;
	case IF_NEQ: return REQUIRED;
	case IF_LT: return REQUIRED;
	case IF_LTE: return REQUIRED;
	case IF_GT: return REQUIRED;
	case IF_GTE: return REQUIRED;
	case JUMP: return REQUIRED;
	case TABLECREATE: return REQUIRED;
	case TABLESETELEM: return REQUIRED;
	case TABLEGETELEM: return REQUIRED;
	case PARAM: return REQUIRED;
	case CALL: return REQUIRED;
	case GETRETVAL: return REQUIRED;
	case RETURN: return REQUIRED;
	case FUNCSTART: return REQUIRED;
	case FUNCEND: return REQUIRED;
	default: return NONE;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr Need result(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case ASSIGN: return REQUIRED;
	case UMINUS: return REQUIRED;
	case ADD: return REQUIRED;
	case SUB: return REQUIRED;
	case MUL: return REQUIRED;
	case DIV: return REQUIRED;
	case MOD: return REQUIRED;
	case NOT: return REQUIRED;
	case AND: return REQUIRED;
	case OR: return REQUIRED;
	case IF_EQ: return REQUIRED;
	case IF_NEQ: return REQUIRED;
	case IF_LT: return REQUIRED;
	case IF_LTE: return REQUIRED;
	case IF_GT: return REQUIRED;
	case IF_GTE: return REQUIRED;
	case JUMP: return REQUIRED;
	case TABLECREATE: return REQUIRED;
	case TABLESETELEM: return REQUIRED;
	case TABLEGETELEM: return REQUIRED;
	case PARAM: return REQUIRED;
	case CALL: return REQUIRED;
	case GETRETVAL: return REQUIRED;
	case RETURN: return REQUIRED;
	case FUNCSTART: return REQUIRED;
	case FUNCEND: return REQUIRED;
	default: return NONE;
	}
}

} // namespace alpha::ir::info_traits
// Follows definitions of all info Traits-Functions of Opcode
namespace alpha::ir::info_traits
{
[[nodiscard]] constexpr bool uses_label(const Opcode opc)
{
	using enum alpha::ir::Opcode;
	switch(opc)
	{
	case IF_EQ: return true;
	case IF_NEQ: return true;
	case IF_LT: return true;
	case IF_LTE: return true;
	case IF_GT: return true;
	case IF_GTE: return true;
	case JUMP: return true;
	default: return false;
	}
}

} // namespace alpha::ir::info_traits

#endif // IR_OPCODE_INFO_TRAITS_HPP

