// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS
// FILE IN ORDER TO MAKE IT MORE READABLE.

#ifndef IR_OPCODE_HPP
#define IR_OPCODE_HPP

#define ALPHA_IROPCODES \
	X(ASSIGN) \
	X(UMINUS) \
	X(ADD) \
	X(SUB) \
	X(MUL) \
	X(DIV) \
	X(MOD) \
	X(NOT) \
	X(AND) \
	X(OR) \
	X(IF_EQ) \
	X(IF_NEQ) \
	X(IF_LT) \
	X(IF_LTE) \
	X(IF_GT) \
	X(IF_GTE) \
	X(JUMP) \
	X(TABLECREATE) \
	X(TABLESETELEM) \
	X(TABLEGETELEM) \
	X(PARAM) \
	X(CALL) \
	X(GETRETVAL) \
	X(RETURN) \
	X(FUNCSTART) \
	X(FUNCEND) 

namespace alpha::ir
{
enum class Opcode
{
	#define X(iropcode) iropcode,
	ALPHA_IROPCODES
	#undef  X
};
} // namespace alpha::ir

#include <string>
namespace alpha::ir
{
[[nodiscard]] std::string to_string(Opcode opc) noexcept;
} // namespace alpha::ir

#endif // IR_OPCODE_HPP

