// This file was generated by `diagnostic_generator`.
// Do not edit manually -- YOUR CHANGES WILL BE OVERWRITTEN.

// IT IS HIGHLY RECOMMENDED TO AUTO-FORMAT THIS
// FILE IN ORDER TO MAKE IT MORE READABLE.

#include <parser/ir_opcode.hpp>
#include <utils/misc.hpp>
namespace alpha::ir
{
std::string to_string(const Opcode opc) noexcept
{
	switch (opc)
	{
		#define X(opc) case Opcode::opc: return Utils::str_to_lower(#opc);
		ALPHA_IROPCODES
		#undef  X
		default:
			UNREACHABLE(FMT::format(
				"BUG: Unknown Opcode. Opcode's int value = `{}`", static_cast<int>(opc)));
	}
}
} // namespace alpha::ir

