- Diagnostic: IMPLICIT_INT_TO_FLOAT_LOSS
  Type: WARNING
  Primary:
    - Message: "integer to floating-point implicit conversion results in integral precision loss"
      Location: conversion_loc

- Diagnostic: ASSIGN_LHS_NOT_LVALUE
  Type: ERROR
  Primary:
    - Message: "Lvalue required as left operand of assignment (found type: {0})"
      Args: [ lhs_type ]
      Location: lhs_loc

- Diagnostic: ASSIGN_TO_FUNC
  Type: ERROR
  Primary:
    - Message: "Assignment of function `{0}`"
      Args: [ func_name ]
      Location: assign_expr_loc
  Notes:
    - Message: "Function `{0}` defined here"
      Args: [ func_name ]
      Location: func_def_loc

- Diagnostic: ASSIGN_TO_LIBFUNC
  Type: ERROR
  Primary:
    - Message: "Assignment of library function `{0}`"
      Args: [ func_name ]
      Location: assign_expr_loc

- Diagnostic: ARITH_OP_NONARITH_OPERAND
  Type: ERROR
  Primary:
    - Message: "`{0}` operand of arithmetic operator `{1}` is never arithmetic -- operand's expression type: `{2}`"
      Args: [ operand_side, operator_symbol, operand_expr_type ]
      Location: operand_loc

- Diagnostic: DIVISION_BY_ZERO
  Type: ERROR
  Primary:
    - Message: "Division by zero"
      Location: division_loc

- Diagnostic: REL_OP_NONARITH_OPERAND
  Type: ERROR
  Primary:
    - Message: "`{0}` operand of relational operator `{1}` is never arithmetic -- operand's expression type: `{2}`"
      Args: [ operand_side, operator_symbol, operand_expr_type ]
      Location: operand_loc

- Diagnostic: UMINUS_NONARITH_OPERAND
  Type: ERROR
  Primary:
    - Message: "operand of unary `-` is never arithmetic"
      Location: operand_loc
  Notes:
    - Message: "operand's expression type: `{0}`"
      Args: [ operand_expr_type ]
      Location: operand_loc

- Diagnostic: INACCESSIBLE_VAR_IN_FUNC
  Type: ERROR
  Primary:
    - Message: "variable `{0}` is not accessible in function `{1}`"
      Args: [ id_name, curr_func_name ]
      Location: var_use_loc
  Notes:
    - Message: "function `{0}` declared here"
      Args: [ curr_func_name ]
      Location: func_decl_loc
    - Message: "variable `{0}` declared here"
      Args: [ id_name ]
      Location: var_decl_loc

- Diagnostic: LOOP_CTRL_KEYWORD_OUTSIDE_LOOP
  Type: ERROR
  Primary:
    - Message: "`{0}` found outside a loop statement"
      Args: [ loop_keyword_name ]
      Location: loop_keyword_loc

- Diagnostic: OPERATOR_REQUIRES_LVALUE
  Type: ERROR
  Primary:
    - Message: "`{0}` `operator{1}` requires an lvalue operand"
      Args: [ op_name, op_symbol ]
      Location: full_expr_loc

- Diagnostic: LOCAL_ID_SHADOWS_LIBFUNC
  Type: ERROR
  Primary:
    - Message: "local identifier `{0}` shadows library function"
      Args: [ libfunc_name ]
      Location: id_use_loc

- Diagnostic: UNRESOLVED_GLOBAL_SYMBOL
  Type: ERROR
  Primary:
    - Message: "symbol `::{0}` not found in global scope"
      Args: [ symbol_name ]
      Location: symbol_use_loc

- Diagnostic: UNCLOSED_COMMENT
  Type: ERROR
  Primary:
    - Message: "unclosed comment, expected terminating `*/` character"
      Location: comment_end_loc
  Notes:
    - Message: "comment starts here"
      Location: comment_start_loc

- Diagnostic: UNCLOSED_STRING
  Type: ERROR
  Primary:
    - Message: "unclosed string literal, expected terminating `\"` character"
      Location: string_end_loc
  Notes:
    - Message: "string literal starts here"
      Location: string_start_loc

- Diagnostic: INVALID_ESCAPE_CODE
  Type: ERROR
  Primary:
    - Message: "invalid escape code `{0}` in string"
      Args: [ escape_code_str ]
      Location: escape_code_loc

- Diagnostic: INVALID_CHARACTER
  Type: ERROR
  Primary:
    - Message: "character `{0}` is invalid"
      Args: [ char_str ]
      Location: char_loc

- Diagnostic: REDEFINITION_OF_LIBFUNC
  Type: ERROR
  Primary:
    - Message: "redefinition of library function `{0}`"
      Args: [ libfunc_name ]
      Location: redef_loc

- Diagnostic: REDEFINITION_OF_FUNC
  Type: ERROR
  Primary:
    - Message: "redefinition of function `{0}`"
      Args: [ func_name ]
      Location: redef_loc
  Notes:
    - Message: "initial definition of function `{0}` here"
      Args: [ func_name ]
      Location: initial_def_loc

- Diagnostic: VAR_REDEFINED_AS_FUNC
  Type: ERROR
  Primary:
    - Message: "`{0}` redefined as a function"
      Args: [ func_name ]
      Location: redef_loc
  Notes:
    - Message: "`{0}` initially defined as a variable here"
      Args: [ func_name ]
      Location: var_def_loc

- Diagnostic: LIBFUNC_REDEFINED_AS_FORMAL_PARAMETER
  Type: ERROR
  Primary:
    - Message: "`{0}` is a library function, can't declare it as formal parameter"
      Args: [ libfunc_name ]
      Location: formal_param_loc

- Diagnostic: REDEFINITION_OF_FORMAL_PARAMETER
  Type: ERROR
  Primary:
    - Message: "redefinition of formal parameter `{0}`"
      Args: [param_name]
      Location: param_loc
  Notes:
    - Message: "initial definition of `{0}` here"
      Args: [param_name]
      Location: initial_param_loc
