- Diagnostic: IMPLICIT_INT_TO_FLOAT_LOSS
  Type: WARNING
  Primary:
    - Message: "integer to floating-point implicit conversion results in integral precision loss"
      Location: conversion_loc

- Diagnostic: ASSIGN_LHS_NOT_LVALUE
  Type: ERROR
  Primary:
    - Message: "Lvalue required as left operand of assignment (found type: {0})"
      Args: [ lhs_type ]
      Location: lhs_loc

- Diagnostic: ASSIGN_TO_FUNC
  Type: ERROR
  Primary:
    - Message: "Assignment of function `{0}`"
      Args: [ func_name ]
      Location: assign_loc
  Notes:
    - Message: "Function `{0}` defined here"
      Args: [ func_name ]
      Location: func_def_loc

- Diagnostic: ASSIGN_TO_LIBFUNC
  Type: ERROR
  Primary:
    - Message: "Assignment of library function `{0}`"
      Args: [ func_name ]
      Location: assign_loc

- Diagnostic: ARITH_OP_NONARITH_OPERAND
  Type: ERROR
  Primary:
    - Message: "`{0}` operand of arithmetic operator `{1}` is never arithmetic"
      Args: [ operand_side, operator_symbol ]
      Location: operand_loc
  Notes:
    - Message: "operand's expression type: `{0}`"
      Args: [ operand_expr_type ]
      Location: operand_loc

- Diagnostic: REL_OP_NONARITH_OPERAND
  Type: ERROR
  Primary:
    - Message: "`{0}` operand of relational operator `{1}` is never arithmetic"
      Args: [ operand_side, operator_symbol ]
      Location: operand_loc
  Notes:
    - Message: "operand's expression type: `{0}`"
      Args: [ operand_expr_type ]
      Location: operand_loc

- Diagnostic: UMINUS_NONARITH_OPERAND
  Type: ERROR
  Primary:
    - Message: "operand of unary `-` is never arithmetic"
      Location: operand_loc
  Notes:
    - Message: "operand's expression type: `{0}`"
      Args: [ operand_expr_type ]
      Location: operand_loc

- Diagnostic: INACCESSIBLE_VARIABLE_IN_FUNC
  Type: ERROR
  Primary:
    - Message: "variable `{0}` is not accessible in function `{1}`"
      Args: [ id_name, curr_func_name ]
      Location: id_loc
  Notes:
    - Message: "function `{0}` declared here"
      Args: [ curr_func_name ]
      Location: curr_func_loc
    - Message: "variable `{0}` declared here"
      Args: [ id_name ]
      Location: var_decl_loc

- Diagnostic: LOOP_CTRL_OUTSIDE_LOOP
  Type: ERROR
  Primary:
    - Message: "`{0}` statement not in a loop statement"
      Args: [ keyword_name ]
      Location: keyword_loc

- Diagnostic: OPERATOR_REQUIRES_LVALUE
  Type: ERROR
  Primary:
    - Message: "{0} operator {1} requires an lvalue operand"
      Args: [ op_name, op_symbol ]
      Location: result_loc
