- Code: ASSIGNMENT_LHS_NOT_LVALUE
  Type: ERROR
  Message: "Lvalue required as left operand of assignment. Left operand's expression type is `{0}`"
  MessageArgs: [ lhs_type ]
  Location: lhs_loc

- Code: ASSIGNMENT_LHS_IS_FUNC
  Type: ERROR
  Message: "Assignment of function `{0}`"
  MessageArgs: [ func_name ]
  Location: assign_loc
  Notes:
    - Message: "Function `{0}` declared here"
      Location: func_decl_loc

- Code: ASSIGNMENT_LHS_IS_LIB_FUNC
  Type: ERROR
  Message: "Assignment of library function `{0}`"
  MessageArgs: [ func_name ]
  Location: assign_loc
